### ISSUE TITLE
Bot not responding after 'adding List' step

### ISSUE THREAD

**Issue by ppremk** [githubtraining/intro-to-html#13]
The bot does not respond after step 9 where users are required to add ordered or unordered list to the index.html. This was reproducible by following the activity instructions and also as reported in the community forum by various users.

[EDIT]
Further investigation shows that this following step is not triggered:

```
- title: Add links
    description: Add links
    event: pull_request.synchronize
    link: '{{ repoUrl }}/pulls'
    actions:
      - type: getFileContents
        filename: index.html
        action_id: index_file
      - type: htmlContainsTag
        html: '%actions.index_file%'
        tag: a
        action_id: contains_a
      - type: gate
        left: '%actions.contains_a%'
        else:
          type: createReview
          body: 09e-links.md
          event: REQUEST_CHANGES
      - type: createReview
        body: 10-merge-third-pr.md
        event: APPROVE 
```
